language: php
sudo: false
php:
    - 5.5
    - 5.6
    - 7.0

env:
  - NEO_VERSION="2.1.6"
  - NEO_VERSION="2.2.6"
  - NEO_VERSION="2.3.0"
  - NEO_VERSION="2.3.1"

before_install:
    - wget dist.neo4j.org/neo4j-enterprise-$NEO_VERSION-unix.tar.gz > null
    - tar -xzf neo4j-enterprise-$NEO_VERSION-unix.tar.gz > null
    - neo4j-enterprise-$NEO_VERSION/bin/neo4j start > null
    - composer self-update

before_script:
    - travis_retry composer install --prefer-source --no-interaction
    - mv tests/database_settings.yml.dist tests/database_settings.yml

script:
    - ./tests/setNeoToken.sh
    - vendor/bin/phpunit

notifications:
    email: "christophe@graphaware.com"
