language: php

php:
    - 5.4
    - 5.5

env:
  - NEO_VERSION="2.1.4"

before_install:
    - sudo apt-get update > /dev/null
    - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz > null
    - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz > null
    - neo4j-community-$NEO_VERSION/bin/neo4j start > null

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction
    - mv tests/database_settings.yml.dist tests/database_settings.yml

script:
    - bin/phpspec run -f dot
    - bin/phpunit

notifications:
    email: "willemsen.christophe@gmail.com"
    